    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials">
      <div class="container">

        <div class="row">
            <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
                <div class="testimonial-item mt-4">
                <img src="assets/img/testimonials/testimonials-3.jpg" class="testimonial-img" alt="">
                <h3><?Php echo $TitMsg; ?></h3>
                <h4>Store Owner</h4>
                <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    <?Php echo $Msg; ?>                    
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
                <p>
                    <button type="submit" name="btnMsgCancela" id="BtnMsgCancela" class="form-submit-button-lg"><?Php echo $btnMsgCancela; ?></button>
                    <button type="submit" name="btnMsgConfirma" id="BtnMsgConfirma" class="form-submit-button-lg"><?Php echo $btnMsgConfirma; ?></button> 
   
                </p>
                </div>
            </div>
        </div>
      </div>
    </section><!-- End Testimonials Section -->
