<style type="text/css">
/*Credits: CSSpplay */
/*URL: http://www.cssplay.co.uk/menus/pro_six */

.menu ul 
{
	margin:0 auto; 
	padding:0; 
	list-style:none; 
	display:table; 
	white-space:nowrap; 
	list-style:none; 
	height:35px; 
	position:relative; 
	background:#fff; 
	font-size:11px;
}
.menu li 
{
	display:table-cell; 
	margin:0; padding:0;
}
.menu li a 
{
	display:block; 
	float:left; 
	height:35px; 
	line-height:30px; 
	color:#333; 
	text-decoration:none; 
	font-family:arial, verdana, sans-serif; 
	font-weight:bold; 
	text-align:center; 
	padding:0 0 0 10px; 
	cursor:pointer; 
	background:url(imagens/menu/pro_six_0a.gif) no-repeat;
}
.menu li a b 
{
	float:left; 
	display:block; 
	padding:0 8px 2px 5px; 
	background:url(imagens/menu/pro_six_0b.gif) no-repeat right top;
}
.menu li.selecionado a 
{
	color:#fff; 
	background:url(imagens/menu/pro_six_2a.gif) no-repeat;
}
.menu li.selecionado a b 
{
	background:url(imagens/menu/pro_six_2b.gif) no-repeat right top;
}
.menu li a:hover 
{
	color:#fff; 
	background: url(imagens/menu/pro_six_1a.gif) no-repeat;
}
.menu li a:hover b 
{
	background:url(imagens/menu/pro_six_1b.gif) no-repeat right top;
}
.menu li.current a:hover 
{
	color:#fff; 
	background: url(imagens/menu/pro_six_2a.gif) no-repeat; cursor:default;
}
.menu li.current a:hover b 
{
	background:url(imagens/menu/pro_six_2b.gif) no-repeat right top;
}

</style>

<!--[if IE]>
<style type="text/css">
.menu ul {display:inline-block;}
.menu ul {display:inline;}
.menu ul li {float:left;}
.menu {text-align:center;}
</style>
<![endif]-->