<style type="text/css">

/*Credits: CSSpplay */
/*URL: http://www.cssplay.co.uk/menus/three */
.menu 
{
	padding:0 0 0 20px; 
	margin:0; 
	list-style:none; 
	height:30px; 
	background: #1841c8 url(imagens/menu/three_0.gif);
}
.menu li {float:left;}
.menu li a 
{
	display:block; 
	float:left; 
	height:30px; 
	line-height:30px; 
	background:url(imagens/menu/three_0.gif); 
	color:#ddd; 
	text-decoration:none; 
	font-family:arial, verdana, sans-serif; 
	text-align:center; 
	padding:0 0 0 10px; 
	cursor:pointer; 
	font-size:11px;
}
.menu li a b 
{
	float:left; 
	display:block; 
	background:url(imagens/menu/three_0.gif) right top; 
	padding:0 16px 0 8px;
}
.menu li.selecionado a 
{
	color:#fff; 
	background:url(imagens/menu/three_2.gif);
}
.menu li.selecionado a b 
{
	background:url(imagens/menu/three_2.gif) no-repeat right top;
}
.menu li a:hover 
{
	color:#fff; 
	background: url(imagens/menu/three_1.gif);
}
.menu li a:hover b 
{
	background:url(imagens/menu/three_1.gif) no-repeat right top;
}
.menu li.selecionado a:hover 
{
	color:#fff; 
	background: url(imagens/menu/three_2.gif); 
	cursor:default;
}
.menu li.selecionado a:hover b 
{
	background:url(imagens/menu/three_2.gif) no-repeat right top;
}
.menu li a em 
{
	display:block; 
	float:left; 
	width:16px; 
	height:30px;
}
.menu li a em.home 
{
	background:url(imagens/menu/home2.gif) no-repeat center center;
}
.menu li a em.login 
{
	background:url(imagens/menu/login.gif) no-repeat center center;
}
.menu li a em.calendar 
{
	background:url(imagens/menu/events.gif) no-repeat center center;
}
.menu li a em.camera 
{
	background:url(imagens/menu/camera.gif) no-repeat center center;
}
.menu li a em.find 
{
	background:url(imagens/menu/find.gif) no-repeat center center;
}
.menu li a em.contact 
{
	background:url(imagens/menu/contact.gif) no-repeat center center;
}
.menu li a em.search 
{
	background:url(imagens/menu/search.gif) no-repeat center center;
}

.menu li a em.adicionar
{
	background:url(imagens/menu/adicionar.gif) no-repeat center center;
}
.menu li a em.ler
{
	background:url(imagens/menu/ler.gif) no-repeat center center;
}
.menu li a em.editar
{
	background:url(imagens/menu/editar.gif) no-repeat center center;
}
.menu li a em.excluir
{
	background:url(imagens/menu/excluir.gif) no-repeat center center;
}
</style>