<style type="text/css">
body {font-size:76%;} 

/*Credits: CSSpplay */
/*URL: http://www.cssplay.co.uk/menus/pro_seven */
.menu ul 
{
	margin:0 auto; 
	padding:0; 
	list-style:none; 
	display:table; 
	white-space:nowrap; 
	list-style:none; 
	height:2em; 
	position:relative; 
	font-size:0.9em;
}
.menu li 
{
	display:table-cell; 
	margin:0; 
	padding:0;
}
.menu li a 
{
	display:block; 
	float:left; 
	height:2em; line-height:2em; 
	color:#333; 
	text-decoration:none; 
	font-family:arial, verdana, sans-serif; 
	font-weight:bold; 
	text-align:center; 
	padding:0 0 0 12px; 
	cursor:pointer; 
	background:url(imagens/menu/pro_seven_0a.gif) no-repeat;
}
.menu li a b 
{
	float:left; 
	display:block; 
	padding:0 12px 0 0; 
	background:url(imagens/menu/pro_seven_0b.gif) no-repeat right top;
}
.menu li.selecionado a 
{
	color:#000; background:url(imagens/menu/pro_seven_2a.gif) no-repeat;
}
.menu li.selecionado a b 
{
	background:url(imagens/menu/pro_seven_2b.gif) no-repeat right top;
}
.menu li.rastro a 
{
	color:#000; 
	background: url(imagens/menu/pro_seven_1a.gif) no-repeat;
}
.menu li.rastro a b 
{
	background:url(imagens/menu/pro_seven_1b.gif) no-repeat right top;
}

.menu li.espaco a 
{
	color:#000; 
	background: url() no-repeat;
}
.menu li.espaco a b 
{
	background:url() no-repeat right top;
}
.menu li.espaco a:hover 
{
	color:#000; 
	background: url() no-repeat;
}
.menu li.espaco a:hover b 
{
	background:url() no-repeat right top;
}

.menu li a:hover 
{
	color:#000; background: url(imagens/menu/pro_seven_1a.gif) no-repeat;
}
.menu li a:hover b 
{
	background:url(imagens/menu/pro_seven_1b.gif) no-repeat right top;
}
.menu li.selecionado a:hover 
{
	color:#000; background: url(imagens/menu/pro_seven_2a.gif) no-repeat; cursor:default;
}
.menu li.selecionado a:hover b 
{
	background:url(imagens/menu/pro_seven_2b.gif) no-repeat right top;
}

</style>

<!--[if IE]>
<style type="text/css">
.menu ul {display:inline-block;}
.menu ul {display:inline;}
.menu ul li {float:left;}
.menu {text-align:center;}
</style>
<![endif]-->