<style type="text/css">

/* ------------------------------------------------------------ MENU 5 --------------------------------------------------------------------------*/	
/*Credits: CSSpplay */
/*URL: http://www.cssplay.co.uk/menus/imagens/menu/pro_five */

.menu 
{
	padding:5px 0 0 1em; 
	margin:0; 
	list-style:none; 
	height:40px; 
	position:relative; 
	background:transparent url(imagens/menu/pro_five_0c.gif) repeat-x left bottom; 
	font-size:11px;
}
.menu li 
{
	float:left; 
	height:40px; 
	margin-right:1px;
}
.menu li a 
{
	display:block; 
	float:left; 
	height:40px; 
	line-height:40px; 
	color:#333; 
	text-decoration:none; 
	font-family:arial, 
	verdana, sans-serif; 
	font-weight:bold; 
	text-align:center; 
	padding:0 0 0 4px; 
	cursor:pointer; 
	background:url(imagens/menu/pro_five_0a.gif) no-repeat;
}
.menu li a b 
{
	float:left; 
	display:block; 
	padding:0 16px 5px 12px; 
	background:url(imagens/menu/pro_five_0b.gif) no-repeat right top;
}
.menu li.selecionado a 
{
	color:#000; 
	background:url(imagens/menu/pro_five_2a.gif) no-repeat;
}
.menu li.selecionado a b 
{
	background:url(imagens/menu/pro_five_2b.gif) no-repeat right top;
}
.menu li.rastro a 
{
	color:#000; 
	background: url(imagens/menu/pro_five_1a.gif) no-repeat;
}
.menu li.rastro a b 
{
	background:url(imagens/menu/pro_five_1b.gif) no-repeat right top;
}

.menu li.espaco a 
{
	color:#000; 
	background: url() no-repeat;
}
.menu li.espaco a b 
{
	background:url() no-repeat right top;
}
.menu li.espaco a:hover 
{
	color:#000; 
	background: url() no-repeat;
}
.menu li.espaco a:hover b 
{
	background:url() no-repeat right top;
}

.menu li a:hover 
{
	color:#000; 
	background: url(imagens/menu/pro_five_1a.gif) no-repeat;
}
.menu li a:hover b 
{
	background:url(imagens/menu/pro_five_1b.gif) no-repeat right top;
}
.menu li.selecionado a:hover 
{
	color:#000; 
	background: url(imagens/menu/pro_five_2a.gif) no-repeat; 
	cursor:default;
}
.menu li.selecionado a:hover b 
{
	background:url(imagens/menu/pro_five_2b.gif) no-repeat right top;
}

/* ---------------------------------------------------------------------------------------------------------------------------------------------*/			

</style>
<?Php