<style type="text/css">
/*Credits: CSSpplay */
/*URL: http://www.cssplay.co.uk/menus/pro_ten */

.menu 
{
	padding:0 0 0 32px; 
	margin:0; list-style:none; 
	height:30px; 
	position:relative;
}
.menu li 
{
	float:left; 
	background:url(imagens/menu/pro_ten_1.gif);
}
.menu li a 
{
	display:block; 
	float:left; 
	height:30px; 
	line-height:29px; 
	background:url(imagens/menu/pro_ten_0.gif) no-repeat; 
	color:#ddd; 
	text-decoration:none; 
	font-size:11px; 
	font-family:arial, verdana, sans-serif; font-weight:bold; 
	text-align:center; 
	padding:0 0 0 15px; 
	cursor:pointer;
}
.menu li a b 
{
	float:left; 
	display:block; 
	padding:0 15px 0 0; 
	background:url(imagens/menu/pro_nine_0.gif) right top;
}
.menu li.selecionado a 
{
	color:#fff; 
	background:url(imagens/menu/pro_ten_2.gif);
}
.menu li.selecionado a b 
{
	background:url(imagens/menu/pro_ten_2.gif) right top;
}
.menu li.rastro a 
{
	color:#fff; 
	background: url(imagens/menu/pro_nine_0.gif) no-repeat;
}
.menu li.rastro a b 
{
	background:url(imagens/menu/pro_nine_0.gif) no-repeat right top;
}

.menu li.espaco a 
{
	color:#fff; 
	background: url(imagens/menu/) no-repeat;
}
.menu li.espaco a b 
{
	background:url(imagens/menu/) no-repeat right top;
}
.menu li.espaco a:hover 
{
	color:#000; 
	background: url(imagens/menu/) no-repeat;
}
.menu li.espaco a:hover b 
{
	background:url(imagens/menu/) no-repeat right top;
}

.menu li a:hover 
{	
	color:#fff; 
	background:url(imagens/menu/pro_ten_1.gif);
}
.menu li a:hover b 
{
	background:url(imagens/menu/pro_ten_1.gif) right top;
}
.menu li.selecionado a:hover 
{
	color:#fff; background:url(imagens/menu/pro_ten_2.gif); 
	cursor:default;
}
.menu li.selecionado a:hover b 
{
	background:url(imagens/menu/pro_ten_2.gif) right top;
}

</style>