<style type="text/css">

/*Credits: CSSpplay */
/*URL: http://www.cssplay.co.uk/menus/pro_two */

.menu 
{
	padding:0 0 0 32px; 
	margin:0; 
	list-style:none; 
	height:35px; 
	background:#fff url(imagens/menu/button1.gif);
	position:relative; 
	border:1px solid #000; 
	border-width:0 1px; 
	border-bottom:1px solid #444;
}
.menu li {float:left;}
.menu li a 
{
	display:block; 
	float:left; 
	height:35px; 
	line-height:35px; 
	color:#aaa; 
	text-decoration:none; 
	font-size:11px; 
	font-family:arial, verdana, sans-serif; 
	font-weight:bold; 
	text-align:center; 
	padding:0 0 0 8px; 
	cursor:pointer;
}
.menu li a b 
{
	float:left; 
	display:block; 
	padding:0 16px 0 8px;
}
.menu li.selecionado a 
{
	color:#fff; background:url(imagens/menu/button3.gif);
}
.menu li.selecionado a b 
{
	background:url(imagens/menu/button3.gif) no-repeat right top;
}
.menu li.rastro a 
{
	color:#FFF; 
	background: url(imagens/menu/button4.gif) no-repeat;
}
.menu li.rastro a b 
{
	background:url(imagens/menu/button4.gif) no-repeat right top;
}

.menu li.espaco a 
{
	color:#000; 
	background: url() no-repeat;
}
.menu li.espaco a b 
{
	background:url() no-repeat right top;
}
.menu li.espaco a:hover 
{
	color:#000; 
	background: url() no-repeat;
}
.menu li.espaco a:hover b 
{
	background:url() no-repeat right top;
}

.menu li a:hover 
{
	color:#fff; background:#000 url(imagens/menu/button4.gif);
}
.menu li a:hover b 
{
	background:url(imagens/menu/button4.gif) no-repeat right top;
}
.menu li.selecionado a:hover 
{
	color:#fff; background:#000 url(imagens/menu/button3.gif); cursor:default;
}
.menu li.selecionado a:hover b 
{
	background:url(imagens/menu/button3.gif) no-repeat right top;
}

</style>