<style type="text/css">

/*Credits: CSSpplay */
/*URL: http://www.cssplay.co.uk/menus/pro_11 */

.menu ul 
{
	margin:0 auto; 
	padding:0; 
	list-style:none; 
	white-space:nowrap; 
	list-style:none;
	height:35px; 
	position:relative; 
	background:#fff; 
	font-size:11px;
}
.menu li 
{
	margin:0 1px 0 0; 
	padding:0; 
	float:left;
}
.menu li a 
{
	display:block; 
	float:left; 
	height:35px; 
	line-height:30px; 
	color:#ddd; 
	text-decoration:none; 
	font-family:arial, verdana, sans-serif; 
	font-weight:bold; 
	text-align:center; 
	padding:0 0 0 10px; 
	cursor:pointer; 
	background:url(imagens/menu/pro_11_0a.gif) no-repeat;
}
.menu li a b 
{
	float:left; 
	display:block; 
	padding:0 8px 5px 5px; 
	background:url(imagens/menu/pro_11_0b.gif) no-repeat right top;
}
.menu li.selecionado a 
{
	color:#fff; 
	background:url(imagens/menu/pro_11_2a.gif) no-repeat; line-height:23px;
}
.menu li.selecionado a b 
{
	background:url(imagens/menu/pro_11_2b.gif) no-repeat right top;
	padding-bottom:12px;
}
.menu li.rastro a 
{
	color:#fff; 
	background: url(imagens/menu/pro_11_1a.gif) no-repeat;
}
.menu li.rastro a b 
{
	background:url(imagens/menu/pro_11_1b.gif) no-repeat right top;
}

.menu li.espaco a 
{
	color:#000; 
	background: url() no-repeat;
}
.menu li.espaco a b 
{
	background:url() no-repeat right top;
}
.menu li.espaco a:hover 
{
	color:#000; 
	background: url() no-repeat;
}
.menu li.espaco a:hover b 
{
	background:url() no-repeat right top;
}
.menu li a:hover 
{
	color:#fff; 
	background: url(imagens/menu/pro_11_1a.gif) no-repeat; 
	line-height:23px;
}
.menu li a:hover b 
{
	background:url(imagens/menu/pro_11_1b.gif) no-repeat right top; 
	padding-bottom:12px;
}
.menu li.selecionado a:hover 
{
	color:#fff; 
	background: url(imagens/menu/pro_11_2a.gif) no-repeat;
	cursor:default;
}
.menu li.selecionado a:hover b 
{
	background:url(imagens/menu/pro_11_2b.gif) no-repeat right top;
}

</style>